{
 "title": "Speedtest",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Download",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "measurement": "download",
     "select": [
      [
       { "params": [ "Int_value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Upload",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "measurement": "upload",
     "select": [
      [
       { "params": [ "Int_value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ping",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "measurement": "ping",
     "select": [
      [
       { "params": [ "Int_value" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}