version: "2.3"

services:
    influxdb:
        image: influxdb:1.5.2-alpine
        volumes:
            - ./influxdb/var/lib:/var/lib/influxdb
            - ./influxdb/etc:/etc/influxdb
        environment:
            - INFLUXDB_ADMIN_USER=admin
            - INFLUXDB_ADMIN_PASSWORD=admin
        ports:
            - 8083:8083
            - 8086:8086

    grafana:
        image: grafana/grafana:5.2.0
        volumes:
            - ./grafana/etc:/etc/grafana
            - ./grafana/var/lib:/var/lib/grafana
            - ./grafana/var/lib/plugins:/var/lib/grafana/plugins
            - ./grafana/var/log:/var/log/grafana
        links:
            - influxdb:influxdb
        ports:
            - 3000:3000

