version: "3.7"

networks:
  home-monitor-net:
    driver: bridge

services:
  influxdb:
    env_file: .env
    image: influxdb:1.5.2
    volumes:
      - ./influxdb/var/lib:/var/lib/influxdb
      - ./influxdb/etc:/etc/influxdb
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - INFLUXDB_USER=${INFLUXDB_USER}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASSWORD}
    ports:
      - 8083:8083
      - 8086:8086
    networks:
      - home-monitor-net

  grafana:
    image: grafana/grafana:5.3.2
    volumes:
      - ./grafana/etc:/etc/grafana
      - ./grafana/var/lib:/var/lib/grafana
      - ./grafana/var/lib/plugins:/var/lib/grafana/plugins
      - ./grafana/var/log:/var/log/grafana
    ports:
      - 3000:3000
    networks:
      - home-monitor-net

  speedtest:
    build: 
      context: ./speedtest
    networks:
      - home-monitor-net
    depends_on:
      - influxdb
    env_file: .env
    environment:
      - LOG_LEVEL=INFO
      - INTERVAL_MINS=5
